<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>JokerScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(\[)([a-zA-Z0-9_]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.jks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.jks</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.jks</string>
				</dict>
			</dict>
			<key>name</key>
			<string>tag.jks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([\w]+)\s*(=)\s*(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.jks</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.jks</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.jks</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.jks</string>
						</dict>
					</dict>
					<key>name</key>
					<string>tag.singlequotes.jks</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>storage.type.label.jks</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([*])([\w-_]+)</string>
							<key>name</key>
							<string>label.tag.jks</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.jks</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([\w ?.,\"_\-*=\(\)]+)</string>
							<key>name</key>
							<string>tag.properties.jks</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([\w]+)\s*(=)\s*(\")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.jks</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.jks</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.jks</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.jks</string>
						</dict>
					</dict>
					<key>name</key>
					<string>tag.doublequotes.jks</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>storage.type.label.jks</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([*])([\w-_]+)</string>
							<key>name</key>
							<string>label.tag.jks</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.jks</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([\w &amp;&gt;&lt;;?.,\'_\-*=\(\)]+)</string>
							<key>name</key>
							<string>tag.properties.jks</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.jks</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.jks</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.jks</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w]+)\s*(=)\s*([\w0-9-_]{0,}+)</string>
					<key>name</key>
					<string>tag.noquotes.jks</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[ 	]{0,}+@([a-zA-Z0-9_]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.jks</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.jks</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\n)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.jks</string>
				</dict>
			</dict>
			<key>name</key>
			<string>tag.jks</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([\w]+)\s*(=)\s*(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.jks</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.jks</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.jks</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.jks</string>
						</dict>
					</dict>
					<key>name</key>
					<string>tag.singlequotes.jks</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>storage.type.label.jks</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([*])([\w-_]+)</string>
							<key>name</key>
							<string>label.tag.jks</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.jks</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([\w ?.,\"_\-*=\(\)]+)</string>
							<key>name</key>
							<string>tag.properties.jks</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([\w]+)\s*(=)\s*(\")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.jks</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.jks</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.jks</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.jks</string>
						</dict>
					</dict>
					<key>name</key>
					<string>tag.doublequotes.jks</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>storage.type.label.jks</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([*])([\w-_]+)</string>
							<key>name</key>
							<string>label.tag.jks</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.jks</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([\w &amp;&gt;&lt;;?.,\'_\-*=\(\)]+)</string>
							<key>name</key>
							<string>tag.properties.jks</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.jks</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.jks</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.jks</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w]+)\s*(=)\s*([\w0-9-_]{0,}+)</string>
					<key>name</key>
					<string>tag.noquotes.jks</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.jks</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;)(?!\[\[).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.jks</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.label.jks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.label.jks</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.jks</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([*])([\w-_]+)\s*|\s*([\w-_ ]+?)</string>
			<key>name</key>
			<string>label.jks</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.name.jks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.name.jks</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.name.jks</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([#])([\w-_]+)\s*|\s*([\w-_ ]+?)</string>
			<key>name</key>
			<string>name.jks</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.cb.jks</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.txt</string>
	<key>uuid</key>
	<string>49f5eb12-68fb-4c54-b1f9-f6441fce02a3</string>
</dict>
</plist>
